### ISSUE TITLE
Getting duplicate symbols error in Xcode 12.2

### ISSUE THREAD

**Issue by samirpramanik** [adjust/cordova_sdk#128]
Hello,

We have upgraded to the latest version of Adjust 4.23.0 and Android works fine.However, we are facing an issue in iOS when trying to build our project on Xcode. We are getting the below error :

> duplicate symbol '_OBJC_CLASS_$_ADJUrlStrategy' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_METACLASS_$_ADJUrlStrategy' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._gdprUrlChoicesArray' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._subscriptionUrlChoicesArray' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._baseUrlChoicesArray' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._choiceIndex' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._startingChoiceIndex' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._wasLastAttemptSuccess' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._overridenGdprUrl' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._overridenSubscriptionUrl' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._overridenBaseUrl' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
duplicate symbol '_OBJC_IVAR_$_ADJUrlStrategy._extraPath' in:
    SampleCord/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(ADJUrlStrategy-8702A38D30AAB0B9.o)
ld: 12 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

We have identified that this comes when we have all_load in the linker flags. If we remove this, the duplicate symbols issue is resolved but we are getting other issues in our application. So, could you look into this issue and suggest us if there is any way to integrate the latest sdk with all_load enabled, because our application needs this flag.
<img width="861" alt="load_all_Xcode" src="https://user-images.githubusercontent.com/48544382/103785055-30bb7a80-5054-11eb-9c64-fbba4905bb69.png">

**Comment by uerceg** [comment]
Hi @samirpramanik 

Hm. Interesting. Do you see same behaviour with **-force_load** instead of **-all_load** and if **-force_load** by some chance fixes the issue, does that linker flag suit the needs of your project as replacement for **-all_load**?

**Comment by samirpramanik** [comment]
Hi @uerceg 

When I change -all_load to -force_load, I get a new error : 
clang: error: no such file or directory: 'AddressBook'
Command Ld failed with a nonzero exit code

**Comment by samirpramanik** [comment]
Also, the older sdk which we were using i.e. 4.14.0 worked fine in our environment, we are seeing this issue after upgrading to 4.23.0

**Comment by uerceg** [comment]
👋 @samirpramanik 

And sorry for big delay in replying in here. Wanted to check if you're still facing this issue with latest SDK version?

Cheers
